from enum import IntEnum

class Action(IntEnum):
    SLEEP_8_HOURS = 0
    
    EAT_LOW_CALORIES_MEAL = 1
    EAT_MEDIUM_CALORIES_MEAL = 2
    EAT_HIGH_CALORIES_MEAL = 3
    EAT_LOW_PROTEIN_MEAL = 4
    EAT_MEDIUM_PROTEIN_MEAL = 5
    EAT_HIGH_PROTEIN_MEAL = 6

    EAT_LOW_FAT_MEAL = 7
    EAT_MEDIUM_FAT_MEAL = 8
    EAT_HIGH_FAT_MEAL = 9

    EAT_LOW_CARBOHYDRATES_MEAL = 10
    EAT_MEDIUM_CARBOHYDRATES_MEAL = 11
    EAT_HIGH_CARBOHYDRATES_MEAL = 12

    EAT_LOW_SATURATED_FAT_MEAL = 13
    EAT_MEDIUM_SATURATED_FAT_MEAL = 14
    EAT_HIGH_SATURATED_FAT_MEAL = 15

    EAT_LOW_FIBER_MEAL = 16
    EAT_MEDIUM_FIBER_MEAL = 17
    EAT_HIGH_FIBER_MEAL = 18

    DO_LIGHT_EXERCISE = 19
    DO_INTERMEDIATE_EXERCISE = 20
    DO_INTENSE_EXERCISE = 21

    REST = 22